version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/menageo 
      - PORT=3000
      - JWT_SECRET=secret
      - JWT_EXPIRES=90d                         
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge